window.portfolioDetails = {
  polestar: ['Experience','15.05.2026 — present','Machine Learning Intern','Polestar Analytics / Polestar LLP · Noida','Joined Polestar Analytics on 15 May 2026 to build production-minded retail ML systems across demand forecasting, uplift modeling, feature engineering, calibration, and scalable Databricks workflows.','Python · pandas · NumPy · scikit-learn · CatBoost · LightGBM · XGBoost · Optuna · PySpark · Databricks','Developing a phased baseline-purchase, promotion-effect, and uplift-estimation pipeline with leakage-safe rolling features.'],
  xceedance: ['Experience','05.2025 — 10.2025','Analyst Programmer Intern','Xceedance Consulting Pvt. Ltd.','An entity extraction and normalization pipeline for commercial insurance documents, resolving the four parties on every risk — Named Insured, Underwriter, Broker, and Reinsurer — out of unstructured policy text. It pairs few-shot Azure OpenAI extraction with a deterministic fuzzy-matching layer that canonicalizes company names against reference databases, surfaced through a Streamlit review tool for human sign-off.','Python · Azure OpenAI · LLMs · Few-shot prompting · Prompt engineering · Named entity recognition · Information extraction · Fuzzy matching · Levenshtein distance · Entity resolution · Data normalization · Synthetic data generation · EDA · Streamlit · pandas · JSON schema validation','Reached 94.2% peak extraction accuracy and 0.91 weighted F1, cutting downstream parsing errors by roughly 15%.'],
  vedvani: ['Experience','05.2024 — 11.2024','Undergraduate Research Intern','Vedvani · Dept. of Computer Science, IIT Kharagpur · Prof. Pawan Goyal','Vedvani is a Vedic Sanskrit speech-to-text system, built during a six-month research internship in the Department of Computer Science at IIT Kharagpur. Starting from a language with no machine-readable speech corpus, the work spans dataset construction, svara-preserving normalization, output-vocabulary expansion, HuBERT-CTC fine-tuning, and language-model decoding — finishing at 17.5% WER and 6.2% CER.','Python · PyTorch · Hugging Face Transformers · HuBERT · Wav2Vec2 · CTC · Speech recognition · Low-resource NLP · Text normalization · KenLM · pyctcdecode · Beam search decoding · librosa · Web scraping · BeautifulSoup · Mixed-precision training','Final system reached 17.5% WER and 6.2% CER on the held-out Vedic test split — a 12% relative WER reduction over the baseline.'],
  'stock-market': ['Project','Quantitative ML / systems','Stock Market Prediction & Trading Simulator','Independent research project','A research-oriented market workflow exploring NSE data, feature engineering, tree-based prediction, market microstructure, order-book signals, backtesting, and trading simulation.','Python · pandas · NumPy · scikit-learn · Random Forest · XGBoost · CatBoost · LightGBM · Backtesting','Combines predictive modeling with realistic evaluation and a simulator designed for future reinforcement-learning experiments.'],
  pokerbots: ['Competition','Game theory / AI','Jane Street Pokerbots','Independent competition','A high-performance poker bot using Monte Carlo estimation and EV-based auction bidding under uncertainty.','Python · Monte Carlo · Game theory','Peak competition rank: #30.'],
  evacuation: ['Project','Computer vision / realtime systems','Real-Time AI Emergency Evacuation System','Independent project','A live vision system that detects people and hazards, maps camera coordinates to a floor plan, and regenerates safe routes.','Python · YOLOv11 · OpenCV · NumPy · A*','30 FPS processing; safe routes regenerated in under 50 ms.'],
  'house-prices': ['Competition','Kaggle / regression','Prediction of House Prices','Kaggle','A feature-rich regression workflow with 200+ engineered features, model comparison, and Bayesian XGBoost tuning.','Python · pandas · scikit-learn · XGBoost · scikit-optimize','90% R²; $25,450 RMSE; Kaggle rank 2,111.'],
  'spaceship-titanic': ['Competition','Kaggle / classification','Spaceship Titanic','Kaggle','A complete passenger-outcome pipeline covering cabin parsing, amenity aggregation, missing values, model comparison, and submission artifacts.','Python · pandas · scikit-learn · GridSearchCV','Public leaderboard score 0.75403; rank 1,582.'],
  titanic: ['Competition','Kaggle / classification','Titanic Survival Prediction','Kaggle','An interpretable survival prediction workflow using EDA, aligned preprocessing, and tuned XGBoost classification.','Python · pandas · scikit-learn · XGBoost','ROC-AUC 0.82–0.88; leaderboard accuracy 0.77511.'],
  'cloud-kitchen': ['Project','Web development','Homecoming Cloud Kitchen Website','Independent project','A responsive static ordering experience with reusable UI, availability states, dynamic pricing, validation, and JSON payload assembly.','HTML · CSS · JavaScript · GitHub Pages','Deployed on GitHub Pages and prepared for API integration.'],
  'image-filtering': ['Project','Computer vision / web','Image Filtering Web App','Independent project','A Flask and OpenCV app that applies image transforms on demand and returns live browser previews through Fetch.','Python · Flask · OpenCV · JavaScript · Fetch API','Delivered a working browser-to-Flask processing loop with cached transforms.'],
  sudoku: ['Project','C++ / interactive graphics','Sudoku Solver','Independent project','An interactive SFML solver that makes recursive backtracking visible through step-by-step progress, conflicts, and hints.','C++ · SFML · Recursion · Backtracking','Demonstrates pruning and event-driven graphics in a focused learning tool.'],
  'academic-outreach': ['Project','Agentic AI / Streamlit','Academic Outreach AI','Independent project','An evidence-first LangGraph pipeline that turns an applicant profile into grounded, reviewable faculty outreach drafts.','Python · LangGraph · Streamlit · Pydantic · SQLite · Gmail API','Reduced the workflow to two LLM calls per email; targeted under ~25 seconds per professor.'],
  'ml-pipeline': ['Project','Machine learning engineering','Classical ML Pipeline','Independent project','A configuration-driven, leakage-safe framework for training, evaluating, reporting, and packaging tabular ML experiments.','Python · pandas · scikit-learn · XGBoost · joblib · Databricks','Reduced runtime ~30%; CV F1 0.74 and ROC-AUC 0.93 on the health task.'],
  'dunnhumby-uplift': ['Project','Forecasting / Databricks','Dunnhumby Uplift & Sales Forecasting','Independent project','Retail demand forecasting across product-week features, intermittent demand modeling, hierarchical approaches, and distributed inference.','Python · CatBoost · PyMC · PySpark · Databricks · MLflow','Produced reusable models, MLflow runs, feature-importance tables, and predictions.'],
  'agentic-poc': ['Project','Agentic systems / inventory','Agentic Inventory-Replenishment POC','Independent project','A supplier-aware replenishment prototype combining demand sizing, eligibility checks, and minimum-order-quantity gating.','Python · LLM workflows · Inventory analytics','Created a constraint-aware, reviewable inventory recommendation flow.'],
  dhruvgpt: ['Project','AI assistant','DhruvGPT','Independent project','A focused personal AI assistant exploration covering prompt behavior, useful interaction boundaries, and a compact interface concept.','Python · LLM APIs · Prompt engineering','Built a small exploration of personal AI product design.']
};

window.detailSections = {
  xceedance: [
    ['01 / The internship', 'Six months inside insurance operations', `<table class="detail-table"><tbody><tr><td>Company</td><td>Xceedance Consulting Pvt. Ltd. — insurance technology and operations</td></tr><tr><td>Duration</td><td>May 2025 — October 2025 (6 months)</td></tr><tr><td>Role</td><td>Analyst programmer intern — document understanding and data quality</td></tr><tr><td>Domain</td><td>Commercial insurance: policy schedules, broker slips, endorsements, underwriting notes</td></tr><tr><td>Deliverable</td><td>End-to-end extraction and normalization pipeline with a reviewer-facing interface</td></tr></tbody></table><p><strong>The brief.</strong> Commercial insurance runs on unstructured documents, and every risk involves four distinct parties that downstream systems must identify correctly. My task was to get those parties out of raw text reliably enough to feed policy administration without a human retyping them.</p><p><strong>Why it was a pipeline, not a model.</strong> Extraction alone is not enough — an extracted name still has to match the same organization already in the master database. So the work split into a probabilistic half (an LLM reading context) and a deterministic half (fuzzy matching against reference data), with an explicit human checkpoint between confident and uncertain results.</p><p><strong>How it was validated.</strong> Live policy data carries PII and PHI, so evaluation ran entirely on a synthetic benchmark I generated to mirror real document structure — which meant I controlled the edge cases and could measure against known ground truth.</p>`, true],
    ['02 / The problem', 'Four roles, one ambiguous sentence', `<p>Accurate risk assessment and legal compliance depend on separating four roles that often appear in the same clause:</p><ul><li><strong>Named Insured</strong> — the primary policyholder or insured entity.</li><li><strong>Underwriter</strong> — the professional or firm assuming the risk.</li><li><strong>Broker</strong> — the intermediary negotiating the policy.</li><li><strong>Reinsurer</strong> — the institution indemnifying the primary insurer.</li></ul><p>Two failure modes made this hard. First, <strong>role ambiguity</strong>: brokers and underwriters are both company names in similar syntactic positions, so position-based rules guess wrong whenever a document deviates from house style. Second, <strong>naming variance</strong>: <em>Acme Corp</em>, <em>Acme Corporation LLC</em>, and <em>Acme Inc.</em> are one counterparty, and a regex parser treats them as three. Manual entry and rule-based parsers both broke on missing role headers, acronyms, and typos.</p>`],
    ['03 / Synthetic evaluation dataset', 'Measuring without touching real policy data', `<p>Rather than evaluate on production documents, I synthesized an annotated benchmark that mimics multi-party insurance schedules, endorsements, and slips — no PII or PHI involved, and ground truth known by construction.</p><ul><li>Gold labels for all four roles, so precision and recall are measurable per role rather than in aggregate.</li><li>Deliberate edge cases: legal-suffix variants, typographical errors, acronyms, and records with role headers removed entirely.</li><li>Because generation was parameterized, hard cases could be over-sampled to stress-test exactly the ambiguities the LLM was expected to resolve.</li></ul>`],
    ['04 / Extraction', 'Few-shot LLM prompting over a fine-tuned NER model', `<p>The obvious approach was fine-tuning a domain NER model (spaCy or BERT). I used few-shot prompting against an Azure OpenAI model instead, because the bottleneck was not pattern recognition — it was <em>contextual role disambiguation</em>, which is exactly what a large model does well without labelled training data an intern-length project could not produce.</p><ul><li><strong>Schema-first prompt:</strong> explicit field definitions for the four roles, so the model is told what distinguishes a broker from an underwriter rather than left to infer it.</li><li><strong>3–5 curated exemplars</strong> chosen specifically for the ambiguous cases — documents where both a broker and an underwriter appear within a few words of each other.</li><li><strong>Constrained JSON output</strong> so responses parse deterministically and a malformed generation fails loudly instead of corrupting the next stage.</li></ul>`],
    ['05 / Normalization', 'Fuzzy matching to a canonical entity', `<p>Extracted strings rarely match master reference records verbatim, so a deterministic normalization layer links each extraction to a canonical entity ID drawn from open-source and internal reference datasets.</p><ul><li><strong>Cleaning:</strong> punctuation stripping, case folding, and truncation of legal tails (<code>Inc.</code>, <code>LLC</code>, <code>GmbH</code>) for the comparison step only — the original string is preserved for audit.</li><li><strong>Similarity scoring:</strong> Levenshtein distance and token-sort ratio, so both character-level typos and reordered word forms are caught.</li><li><strong>Threshold routing:</strong> scores <strong>≥ 85%</strong> auto-link to the canonical ID; <strong>60–85%</strong> are flagged for human validation; below that, no match is asserted.</li></ul><p>The banded thresholds matter more than the metric choice: they convert a continuous confidence score into three explicit outcomes, so the system never silently guesses on an uncertain match.</p>`],
    ['06 / Review interface', 'A Streamlit surface for human-in-the-loop sign-off', `<p>The pipeline was wrapped in an interactive Streamlit app so underwriters and data specialists could actually use it rather than reading logs.</p><ul><li>Upload raw document text or batches of files.</li><li>Inspect extracted entities side by side with the source text, so a reviewer can verify a decision without leaving the tool.</li><li>Review canonical mappings and clear the flags raised by the 60–85% similarity band.</li></ul>`],
    ['07 / Results', 'Evaluated on the synthetic benchmark', `<table class="detail-table"><tbody><tr><td>Peak extraction accuracy</td><td><strong>94.2%</strong></td></tr><tr><td>Weighted F1-score</td><td><strong>0.91</strong></td></tr><tr><td>Downstream parsing errors</td><td><strong>~15% reduction</strong></td></tr></tbody></table><ul><li><strong>Context beat position.</strong> Few-shot prompting produced the largest gains precisely where rule-based parsing failed — sentences containing both a broker and an underwriter in close proximity.</li><li><strong>Normalization removed redundancy.</strong> Consolidating name variants into one canonical form collapsed duplicate counterparties that had previously entered the data store as separate records.</li><li><strong>The gain was downstream.</strong> Feeding normalized output into policy processing cut structural parsing errors by roughly 15%, which is where the operational value actually landed.</li></ul>`, true],
    ['08 / Pipeline at a glance', '', `<ol><li>Ingest unstructured insurance text — schedules, slips, endorsements, notes.</li><li>Extract the four party roles with a schema-constrained few-shot Azure OpenAI prompt.</li><li>Parse the constrained JSON response into typed records.</li><li>Clean and tokenize each entity string for comparison.</li><li>Score against reference master data using Levenshtein and token-sort ratio.</li><li>Auto-link, flag for review, or reject based on the similarity band.</li><li>Present extractions and mappings in Streamlit for human approval.</li><li>Emit canonicalized records to downstream policy administration.</li></ol>`],
    ['09 / Technologies and methods', 'The full stack, by layer', `<table class="detail-table"><tbody><tr><td>Language &amp; environment</td><td>Python 3, Jupyter notebooks, Git</td></tr><tr><td>Generative AI</td><td>Azure OpenAI, large language models, few-shot prompting, schema-first prompt design, exemplar selection for ambiguous cases</td></tr><tr><td>Structured output</td><td>JSON-constrained generation, response schema validation, typed record parsing, fail-loud error handling</td></tr><tr><td>NLP</td><td>Named entity recognition, information extraction, entity resolution, contextual role disambiguation</td></tr><tr><td>String matching</td><td>Levenshtein distance, token-sort ratio, Python fuzzy string-matching libraries, banded similarity thresholds</td></tr><tr><td>Data normalization</td><td>Punctuation and case normalization, legal-suffix truncation, canonical ID linkage against open-source and master reference datasets</td></tr><tr><td>Data engineering</td><td>pandas, synthetic dataset generation, ground-truth annotation, batch file ingestion, CSV/JSON handling</td></tr><tr><td>Analysis</td><td>Exploratory data analysis, data cleaning and standardization, inconsistency profiling across entity fields</td></tr><tr><td>Interface</td><td>Streamlit web application, side-by-side extraction review, human-in-the-loop approval flags</td></tr><tr><td>Evaluation</td><td>Accuracy, precision, recall, weighted F1-score, per-role error analysis, downstream parse-error tracking</td></tr></tbody></table>`, true]
  ],
  vedvani: [
    ['01 / The internship', 'Six months on the Vedic ASR track', `<table class="detail-table"><tbody><tr><td>Host</td><td>Department of Computer Science, IIT Kharagpur</td></tr><tr><td>Supervisor</td><td>Prof. Pawan Goyal</td></tr><tr><td>Duration</td><td>May 2024 — November 2024 (6 months)</td></tr><tr><td>Role</td><td>Undergraduate research intern — dataset construction and acoustic modeling</td></tr><tr><td>Deliverable</td><td>End-to-end Vedic Sanskrit speech-to-text pipeline, from raw recitations to WER/CER numbers</td></tr></tbody></table><p><strong>The brief.</strong> Make automatic speech recognition work for recited Vedic Sanskrit — a language with an enormous oral tradition and essentially no machine-readable audio–text dataset to train on.</p><p><strong>Why it was really two projects.</strong> The first half was data: find recitation audio, find the matching verse text, align the two, and produce splits a model can consume. The second half was modeling: adapt a large self-supervised speech encoder to Vedic phonetics and measure it honestly against a baseline.</p><p><strong>How it ran.</strong> Training and evaluation happened on the department's GPU cluster. The system is a set of standalone scripts and notebooks rather than a deployed service — the right shape for research iteration, where each stage needs to be rerunnable in isolation.</p>`, true],
    ['02 / The problem', 'Why general ASR fails on Vedic Sanskrit', `<p>Vedic Sanskrit is preserved through recitation, and the recitation is the point: pitch accent is meaning-bearing. In text this shows up as <em>svara</em> markers — udātta (U+0951), anudātta (U+0952), the vowel sign U+0962 — alongside characters like ॐ and the danda (।).</p><p>Off-the-shelf systems are trained for modern Hindi or standard Sanskrit and cannot emit those symbols at all. Strip them to fit an existing vocabulary and you throw away exactly the information a Vedic transcript exists to record. Keeping them was therefore a hard constraint on every stage — scraping, normalization, tokenizer, and the model's output layer.</p>`],
    ['03 / Corpus and dataset construction', 'From scattered recitations to train/val/test', `<p>Verse transcripts were scraped and consolidated into a single UTF-8 Devanagari corpus of roughly <strong>30,785 verse lines</strong>, then paired clip-by-clip with recitation audio into a filename → transcript mapping of <strong>30,779 rows</strong>.</p><ul><li>Splits: <strong>24,623</strong> train / <strong>3,078</strong> validation / <strong>3,078</strong> test, each row carrying path, transcript, and clip duration.</li><li>Clips longer than <strong>30 seconds</strong> were filtered out to keep activation memory bounded on a single GPU.</li><li>All audio decoded to mono <strong>16 kHz</strong> with librosa, normalized by the feature extractor with attention masks returned.</li></ul>`],
    ['04 / Normalization and tokenization', 'Cleaning text without flattening the accents', `<p>Transcript cleaning removes Latin and Devanagari digits, structural punctuation left over from scraping, and collapses whitespace — while deliberately leaving every accent mark untouched.</p><p>Tokenization is <strong>character-level</strong> rather than word-level: Vedic vocabulary is effectively open, so word units guarantee out-of-vocabulary failure. The vocabulary is derived from the corpus itself — sorted unique characters plus <code>[UNK]</code>, <code>[PAD]</code>, and the word-delimiter <code>|</code> — giving a <strong>74-token</strong> tokenizer that is regenerable from the text at any time.</p>`],
    ['05 / Expanding the model vocabulary', 'Making svara characters decodable at all', `<p>The pre-trained checkpoint's configuration (inherited from <code>facebook/wav2vec2-large-xlsr-53</code>) exposes a <strong>64-token</strong> output head containing none of the Vedic accent characters. A CTC model can only ever predict symbols that exist in its final linear layer, so fine-tuning as-is would have been incapable of producing a correct Vedic transcript.</p><p>The fix is small but load-bearing: pass <code>vocab_size=len(processor.tokenizer)</code> (74) with <code>ignore_mismatched_sizes=True</code>, which makes Transformers re-initialize the CTC classification head at the larger size while loading every pre-trained encoder weight unchanged. The head learns the new svara symbols during fine-tuning; the acoustic representation is inherited intact.</p>`],
    ['06 / Auditing the data', 'Quantifying alignment noise before trusting a metric', `<p>Because the mapping and the training split were maintained separately, I wrote a verification pass that re-checks every training row's transcript against the canonical mapping by exact string match and writes both a full results table and an isolated mismatch file.</p><p><strong>14,625 of 24,623 training rows (≈59%) disagreed.</strong> That number reframed the rest of the project: it puts a hard ceiling on achievable WER, explains residual error that no amount of tuning removes, and identifies alignment — not architecture — as the highest-leverage thing left to fix. Measuring it was more useful than quietly training on it.</p>`, true],
    ['07 / Model and training setup', 'HuBERT-CTC fine-tuning in a custom loop', `<p>The acoustic model is <code>HubertForCTC</code> fine-tuned from a HuBERT checkpoint over a wav2vec2-large-xlsr architecture. I used an explicit PyTorch training loop instead of the Hugging Face <code>Trainer</code> to control per-epoch evaluation, logging, checkpointing, and memory behaviour on a shared cluster.</p><table class="detail-table"><tbody><tr><td>Architecture</td><td>24 transformer layers, hidden 1024, 16 heads, 7-layer convolutional feature encoder</td></tr><tr><td>Objective</td><td>CTC, mean loss reduction, 74-token character vocabulary</td></tr><tr><td>Optimizer / LR</td><td>AdamW, 1e-5, linear schedule with 1,500 warmup steps</td></tr><tr><td>Batching</td><td>12 train / 4 eval, gradient accumulation 2 (effective batch 24)</td></tr><tr><td>Epochs</td><td>30, checkpoint and eval written after every epoch</td></tr><tr><td>Precision</td><td>FP16 autocast with gradient scaling</td></tr><tr><td>Memory</td><td>Gradient checkpointing, frozen feature extractor, periodic CUDA cache flush</td></tr><tr><td>Regularization</td><td>Attention/hidden dropout 0.1, layerdrop 0.1, SpecAugment time-mask probability 0.05</td></tr><tr><td>Logging</td><td>Per-epoch eval loss, WER, and CER appended to a plain-text training log</td></tr></tbody></table>`, true],
    ['08 / Decoding and evaluation', 'Greedy CTC, then a 4-gram language model', `<p>Two decoding paths were evaluated on the same held-out split. The first is greedy CTC — argmax over frame logits, collapsed and detokenized. The second adds an external <strong>KenLM 4-gram</strong> language model through a <code>pyctcdecode</code> beam decoder wrapped in a LM-aware processor, so acoustically ambiguous frames get resolved against Vedic word statistics.</p><ul><li>Metrics: <strong>WER and CER</strong>, computed per sample and written to CSV alongside the reference and hypothesis, with an aggregate row.</li><li>Test set: <strong>3,074</strong> scored clips.</li><li>Baseline reference: a Hindi XLSR model probed on Common Voice Hindi, to keep the Sanskrit numbers in context.</li></ul><table class="detail-table"><tbody><tr><td>Word error rate</td><td><strong>17.5%</strong></td></tr><tr><td>Character error rate</td><td><strong>6.2%</strong></td></tr><tr><td>Vs. baseline</td><td>12% relative WER reduction</td></tr></tbody></table><p>The gap between the two rates is the interesting part: a CER of 6.2% against a WER of 17.5% says the acoustic model hears the phonemes well and most word-level errors come from a handful of characters — accent marks and sandhi boundaries — rather than from wholesale mishearing.</p>`],
    ['09 / Pipeline at a glance', '', `<ol><li>Scrape and consolidate the Vedic verse corpus.</li><li>Pair audio clips with verses; emit the canonical mapping.</li><li>Build the 74-token character tokenizer from the corpus.</li><li>Split into train/validation/test; filter clips over 30 s.</li><li>Verify every training transcript against the mapping.</li><li>Fine-tune HuBERT-CTC with the resized output head.</li><li>Decode greedily and with the KenLM 4-gram; report WER/CER.</li></ol>`],
    ['10 / Technologies and methods', 'The full stack, by layer', `<table class="detail-table"><tbody><tr><td>Language &amp; environment</td><td>Python 3, Jupyter notebooks, Linux GPU cluster with CUDA, Git</td></tr><tr><td>Deep learning</td><td>PyTorch, custom training loop, AdamW, linear warmup schedule, FP16 autocast with gradient scaling, gradient checkpointing, gradient accumulation</td></tr><tr><td>Speech models</td><td>HuBERT, Wav2Vec2 / XLS-R architecture lineage, self-supervised speech representations, transfer learning, frozen convolutional feature encoder, SpecAugment time masking</td></tr><tr><td>Sequence modeling</td><td>Connectionist Temporal Classification (CTC), character-level modeling, output-head resizing for vocabulary expansion</td></tr><tr><td>Hugging Face stack</td><td>Transformers (<code>HubertForCTC</code>, <code>Wav2Vec2CTCTokenizer</code>, <code>Wav2Vec2FeatureExtractor</code>, <code>Wav2Vec2Processor</code>), Datasets, Evaluate</td></tr><tr><td>Audio processing</td><td>librosa, torchaudio, soundfile, 16 kHz resampling, mono decoding, amplitude normalization, duration filtering, low-resource augmentation</td></tr><tr><td>Language modeling &amp; decoding</td><td>Greedy CTC decoding, pyctcdecode beam search, KenLM 4-gram n-gram model, LM-aware processor for rescoring</td></tr><tr><td>Text &amp; Unicode</td><td>Devanagari normalization, svara-preserving cleaning, Unicode-aware regex, corpus-derived character tokenizer construction</td></tr><tr><td>Data engineering</td><td>BeautifulSoup web scraping, audio–text alignment, pandas, NumPy, CSV split management, exact-match dataset verification</td></tr><tr><td>Evaluation</td><td>Word error rate, character error rate, per-sample error reporting, baseline comparison against a Hindi XLSR model on Common Voice</td></tr></tbody></table>`, true]
  ]
};

const data = window.portfolioDetails;
const item = data[document.body.dataset.detail];
if (item) {
  document.title = `${item[2]} — Dhruv Varshney`;
  const detailMedia = {
    'stock-market': ['images/stock-price-prediction.png', 'Stock market prediction visualization', 'Stock market simulation and prediction visual.'],
    pokerbots: ['poker.jpg', 'Jane Street Pokerbots visual', 'Competition visual for the poker bot strategy project.'],
    evacuation: ['images/emergency-evacuation.png', 'Emergency evacuation system floor-map output', 'Evacuation routing output under dynamic hazards.'],
    'house-prices': ['images/house-price-prediction.png', 'House price prediction dashboard', 'Regression quality and prediction example from the housing workflow.'],
    'spaceship-titanic': ['images/Stöwer_Titanic.jpg', 'Historical Titanic image used as thematic visual for the Spaceship Titanic challenge', 'Thematic visual context for the Spaceship Titanic prediction challenge.'],
    titanic: ['images/Stöwer_Titanic.jpg', 'Historical depiction of the RMS Titanic sinking', 'Historical context image for the Titanic challenge.'],
    'cloud-kitchen': ['images/hcck.png', 'cloud kitchen project page', 'Temporary visual placeholder until a dedicated Cloud Kitchen project image is added.'],
    sudoku: ['images/sudoku.jpg', 'Sudoku board used by the solver', 'Sudoku board configuration used for solver demonstrations.'],
    'academic-outreach': ['images/dhruvgpt.png', 'Academic Outreach AI', 'Temporary visual placeholder until a dedicated Academic Outreach AI image is added.'],
    'image-filtering': ['images/image-processing.png', 'Computer vision image-filtering comparison', 'Comparative output of common computer vision filters.'],
    'ml-pipeline': ['images/machine-learning-pipeline.png', 'Classical machine learning pipeline architecture', 'End-to-end architecture of the classical ML framework.'],
    'dunnhumby-uplift': ['images/dunnhumby.png', 'Dunnhumby forecasting pipeline architecture', 'Production-oriented forecasting and evaluation stack.'],
    'agentic-poc': ['images/dhruvgpt.png', 'Agentic Inventory-Replenishment POC', 'Temporary visual placeholder until a dedicated Agentic POC image is added.'],
    dhruvgpt: ['images/dhruvgpt.png', 'DhruvGPT system architecture and flow', 'Backend, streaming, and persistence design for DhruvGPT.']
  };
  const detailRepos = {
    vedvani: 'https://github.com/dhruvvarshney1/sanskrit-asr-system'
  };
  const repo = detailRepos[document.body.dataset.detail];
  const repoMarkup = repo
    ? `<a class="detail-repo" href="${repo}" target="_blank" rel="noopener"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.2c3-.3 6-1.5 6-6.5a4.6 4.6 0 0 0-1.3-3.2 4.2 4.2 0 0 0-.1-3.2s-1.1-.3-3.5 1.3a12.3 12.3 0 0 0-6.2 0C6.5 2.8 5.4 3.1 5.4 3.1a4.2 4.2 0 0 0-.1 3.2A4.6 4.6 0 0 0 4 9.5c0 5 3 6.2 6 6.5a4.8 4.8 0 0 0-1 3.2v4"></path></svg><span>${repo.replace('https://', '')}</span></a>`
    : '';
  const media = detailMedia[document.body.dataset.detail];
  const figureMarkup = media
    ? `<figure class="detail-visual has-image reveal is-visible" role="img" aria-label="${media[1]}"><img class="detail-image" src="${media[0]}" alt="${media[1]}" loading="lazy" decoding="async"><figcaption>${media[2]}</figcaption></figure>`
    : `<figure class="detail-visual reveal is-visible" role="img" aria-label="Visual overview for ${item[2]}"><div class="visual-mark"><span>${item[2][0]}</span><span>${item[2].split(' ')[1]?.[0] || '·'}</span></div><figcaption>Project visual · Add a repository screenshot or demo capture when available.</figcaption></figure>`;
  const bullets = ['Designed the end-to-end workflow and implementation.', 'Evaluated edge cases and kept outputs reproducible.', 'Documented decisions, trade-offs, and the path to future integration.'];
  // Sections are [eyebrow, heading, html, wide?]. Default is the generic template; a key in
  // detailSections replaces it with a hand-written writeup.
  const genericSections = [
    ['01 / Overview & objective', 'What this work set out to do', `<p>${item[4]}</p>`],
    ['02 / Responsibilities', '', `<ul>${bullets.map(x => `<li>${x}</li>`).join('')}</ul>`],
    ['03 / Technologies used', '', `<div class="tags">${item[5].split(' · ').map(x => `<span class="tag">#${x}</span>`).join('')}</div>`],
    ['04 / Features', '', '<ul><li>Responsive, modular implementation</li><li>Clear user-facing outputs</li><li>Measured performance and quality checks</li></ul>'],
    ['05 / Challenges & solution', '', '<p>The main challenge was balancing useful output with practical constraints. I kept the core flow explicit, validated intermediate results, and optimized the smallest bottleneck that mattered.</p>'],
    ['06 / Achievements & outcomes', '', `<ul><li>${item[6]}</li><li>Created a maintainable foundation for future iteration.</li></ul>`]
  ];
  const sections = (window.detailSections || {})[document.body.dataset.detail] || genericSections;
  const sectionMarkup = sections.map(([eyebrow, heading, html, wide]) =>
    `<section${wide ? ' class="detail-wide"' : ''}><p class="eyebrow">${eyebrow}</p>${heading ? `<h2>${heading}</h2>` : ''}${html}</section>`
  ).join('');
  document.querySelector('#detail').innerHTML = `<a class="back-link" href="index.html">← Back to portfolio</a><header class="detail-hero reveal is-visible"><p class="eyebrow">${item[0]} · ${item[1]}</p><h1>${item[2]}</h1><p class="detail-org">${item[3]}</p><p class="detail-overview">${item[4]}</p>${repoMarkup}</header>${figureMarkup}<div class="detail-grid">${sectionMarkup}</div>`;
}

(() => {
  const nav = document.getElementById('navbar');
  if (!nav) {
    return;
  }

  const sampleFractions = [0.25, 0.5, 0.75];
  let framePending = false;

  const parseColor = value => {
    const match = value.match(/rgba?\(([^)]+)\)/i);
    if (!match) {
      return null;
    }

    const parts = match[1].split(',').map(part => part.trim());
    if (parts.length < 3) {
      return null;
    }

    return {
      red: Number(parts[0]),
      green: Number(parts[1]),
      blue: Number(parts[2]),
      alpha: parts[3] === undefined ? 1 : Number(parts[3])
    };
  };

  const backdropColor = element => {
    for (let current = element; current && current !== document.documentElement; current = current.parentElement) {
      const style = getComputedStyle(current);
      const color = parseColor(style.backgroundColor);
      if (color && color.alpha > 0) {
        return color;
      }
    }

    const bodyColor = parseColor(getComputedStyle(document.body).backgroundColor);
    if (bodyColor && bodyColor.alpha > 0) {
      return bodyColor;
    }

    return { red: 255, green: 255, blue: 255, alpha: 1 };
  };

  const isLightBackdrop = element => {
    const color = backdropColor(element);
    return (0.299 * color.red + 0.587 * color.green + 0.114 * color.blue) >= 160;
  };

  const updateNavTone = () => {
    const rect = nav.getBoundingClientRect();
    const sampleY = Math.min(rect.bottom - 1, rect.top + rect.height * 0.5);
    const lightSamples = sampleFractions.reduce((count, fraction) => {
      const sampleX = rect.left + rect.width * fraction;
      const topElement = document.elementsFromPoint(sampleX, sampleY).find(element => !nav.contains(element));
      return count + (topElement && isLightBackdrop(topElement) ? 1 : 0);
    }, 0);

    nav.classList.toggle('nav-on-light', lightSamples >= 2);
  };

  const scheduleUpdate = () => {
    if (framePending) {
      return;
    }

    framePending = true;
    requestAnimationFrame(() => {
      framePending = false;
      updateNavTone();
    });
  };

  window.addEventListener('scroll', scheduleUpdate, { passive: true });
  window.addEventListener('resize', scheduleUpdate);
  window.addEventListener('load', scheduleUpdate, { once: true });
  scheduleUpdate();
})();
